# Generated by Django 5.1.3 on 2024-11-24 14:46

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('144', '144p'), ('360', '360p'), ('480', '480p'), ('720', '720p'), ('1080', '1080p')], max_length=16),
        ),
    ]
